### ISSUE TITLE
Implement a minor mode

### ISSUE THREAD

**Issue by PythonNut** [7696122/evil-terminal-cursor-changer#10]
I think this would be much more useful if there were an easy way to disable this package dynamically. 

I'd consider adding this to my config, but it doesn't work in certain terminals, and I need a way to disable it quickly when that happens.

The simplest, and most intuitive, way to do this is to implement a minor mode, which can be toggled with ease, both by the user and programmatically.

**Comment by 7696122** [comment]
12d6a337596ee05c4b246972df329b7b6877276d 
Add activate, deactivate function.
