### ISSUE TITLE
Can't resize font for KDE Konsole

### ISSUE THREAD

**Issue by willghatch** [7696122/evil-terminal-cursor-changer#11]
When using evil-terminal-cursor-changer within a KDE Konsole terminal, the font will always be resized to the default Konsole profile size.  So if I try to resize the font in Konsole (eg. using Ctrl+mouse-wheel) it will resize for milliseconds before switching back to its original size.  If I don't use this package everything works as I would normally expect.

**Comment by 7696122** [comment]
Can you show me screenshot?

**Comment by willghatch** [comment]
Now that I try it again, the issue went away... so I'm not sure what caused it or what changed.  But now in Konsole and Cool-retro-term I see issue #8 instead.  I'm not sure what happened or why the resize issues went away, but I'll close this.
