### ISSUE TITLE
Error in post-command-hook (etcc-evil-set-cursor):  (void-variable seq)

### ISSUE THREAD

**Issue by tsandstr** [7696122/evil-terminal-cursor-changer#19]
Config code copied directly from github. This is the result. 
```
Error in post-command-hook (etcc-evil-set-cursor):  (void-variable seq)
```

**Comment by Shtucer** [comment]
Set cursor shapes BEFORE loading extension
Your config might look like this
```
(setq evil-motion-state-cursor 'box)  ; █
(unless (display-graphic-p)                                                                                                              
  (require 'evil-terminal-cursor-changer)                                                                                                
  (evil-terminal-cursor-changer-activate))
```

**Comment by srustamo** [comment]
> Set cursor shapes BEFORE loading extension
> Your config might look like this
> 
> ```
> (setq evil-motion-state-cursor 'box)  ; █
> (unless (display-graphic-p)                                                                                                              
>   (require 'evil-terminal-cursor-changer)                                                                                                
>   (evil-terminal-cursor-changer-activate))
> ```

Does not help.

**Comment by io12** [comment]
Doesn't help for me either

**Comment by wojtekgalaj** [comment]
This worked for me.
```  
  (unless (display-graphic-p)
      (use-package evil-terminal-cursor-changer
        :ensure t
        :init
        (setq evil-motion-state-cursor 'box)  ; █
        (setq evil-visual-state-cursor 'box)  ; █
        (setq evil-normal-state-cursor 'box)  ; █
        (setq evil-insert-state-cursor 'bar)  ; ⎸
        (setq evil-emacs-state-cursor  'hbar) ; _
        :config
        (etcc-on)
        ))
```

**Comment by io12** [comment]
Works for me too, thanks!
