### ISSUE TITLE
Does not work in iTerm2 with Emacs 24.4.1

### ISSUE THREAD

**Issue by danielwuz** [7696122/evil-terminal-cursor-changer#3]
In latest Emacs version, this mode breaks. 

I debugged a little bit, that's because variables `etcc--evil-emacs-state-cursor` evaluates to be a color value like "gray", rather than a shape symbol. Then all `if` condition failed in `etcc--set-evil-cursor`, therefore none of the set cursor function gets called, as in https://github.com/7696122/evil-terminal-cursor-changer/blob/master/evil-terminal-cursor-changer.el#L184

My emacs version:
```
"GNU Emacs 24.4.1 (x86_64-apple-darwin14.0.0, NS apple-appkit-1343.16)
 of 2015-01-09 on dawu.local"
```

Let me know if there's any information I can provide or anything I can do to help solve this problem.

**Comment by 7696122** [comment]
Sorry, I'm so late to fix this bug. I mistake evil cursor type setting. 

My evil setting `'(bar "red"). so i use car to get first element. 

but normally settings is `("red" bar)'.

So I make function for find "bar, box, box' symbol.

**Comment by danielwuz** [comment]
@7696122 It now works, just verified. Thanks very much for your hard work!
