### ISSUE TITLE
Doesn't work in mintty

### ISSUE THREAD

**Issue by edvail** [7696122/evil-terminal-cursor-changer#4]
Hi.
Cursor doesn't change in mintty.
mintty supports DECSCUSR sequences:
# blinking block
printf '\e[1 q'
# steady block
printf '\e[2 q'
# blinking underscore
printf '\e[3 q'
# steady underscore
printf '\e[4 q'
# blinking bar
printf '\e[5 q'
# steady bar
printf '\e[6 q'
----------------
Only one of used environment variables provide some info:
(getenv "TERM_PROGRAM")
nil
(getenv "KONSOLE_PROFILE_NAME")
nil
(getenv "XTERM_VERSION")
nil
(getenv "COLORTERM")
nil
(getenv "TMUX")
"/tmp/tmux-1000/default,1167,1"

**Comment by 7696122** [comment]
Please let me know result of "(getenv "XTERM_VERSION")" in mintty.

**Comment by 7696122** [comment]
Sorry.  I miss you report. 
(getenv "XTERM_VERSION")
nil

**Comment by 7696122** [comment]
Please let me know result of "(getenv "TERM")" in mintty.

https://www.cygwin.com/ml/cygwin/2011-03/msg00121.html

**Comment by edvail** [comment]
(getenv "TERM")
"dumb"

**Comment by 7696122** [comment]
I add to support dumb(mintty) at ac1c8e0628cbca86f88a7a04dc405a4a3c3deda4.
I don't use mintty, so test in mintty, plz.

**Comment by edvail** [comment]
Thank you @7696122 !
Works like a charm!
Thank you very much!

Excited by results, I imagine one more thing - cursor color.
[There](https://github.com/mintty/mintty/blob/master/wiki/Tips.md#changing-colours) is described how to change cursor color: `echo -ne '\e]12;#00FF00\a'  # Green cursor`
So, can that be implemented in this package or should it be another one?

**Comment by 7696122** [comment]
90cc8a72bbf54710fcbfbcc700a2f648bfb18ab5

check this. implemented cursor color.
