### ISSUE TITLE
Error in post-command-hook (etcc--set-evil-cursor): (void-function hexrgb-rgb-hex-string-p)

### ISSUE THREAD

**Issue by edvail** [7696122/evil-terminal-cursor-changer#6]
Sorry :) but now i have another error message: ```Error in post-command-hook (etcc--set-evil-cursor): (void-function hexrgb-rgb-hex-string-p)```
Still same cursor settings:
```
    (setq evil-emacs-state-cursor "violet")
    (setq evil-insert-state-cursor '("blue" (bar . 2)))
    (setq evil-motion-state-cursor "magenta")
    (setq evil-normal-state-cursor "green")
    (setq evil-operator-state-cursor '("cyan" evil-half-cursor))
    (setq evil-replace-state-cursor '("red" hbar))
    (setq evil-visual-state-cursor "orange")
```

**Comment by 7696122** [comment]
plz, comment your emacs version.

**Comment by edvail** [comment]
GNU Emacs 24.5.1 (i686-pc-mingw32)
 of 2015-04-11 on LEG570

**Comment by edvail** [comment]
GNU Emacs 24.5.1 (x86_64-unknown-cygwin)
 of 2015-06-23 on desktop-new

**Comment by 7696122** [comment]
evil-terminal-cursor-changer require hexrgb.el(http://emacswiki.org/emacs/hexrgb.el).
you can install from elpa.

I fix some bugs and do refactoring code.
check this. 
3a8172064236f3da9f1635092ab71baa9b288ff
