### ISSUE TITLE
broken on transparent iterm2

### ISSUE THREAD

**Issue by huahaiy** [7696122/evil-terminal-cursor-changer#7]
I use spacemacs (which includes this package by default) under vim mode in iterm2 terminal. Updating to the lasted version of this package (Aug. 24) breaks the terminal scrolling on both iterm2.1.1 and the 2.9 beta. The symptom are: 1. lags in normal model "j" "k" scrolling; 2. left over characters on screen before and after scroll, such as 0, 7, or \, depending on which version of this package I tried; 3. sometimes the whole line become left over on screen.

I tracked your commit history and found that the versions after commit https://github.com/7696122/evil-terminal-cursor-changer/commit/90cc8a72bbf54710fcbfbcc700a2f648bfb18ab5#diff-8c0163553d7fc188a6d08c9f515df9cd on Aug. 19 are all broken. The Aug.19 version will leave \, whereas the latter versions leave 7, or 0, etc. Revert back to version on Aug. 17 solves all the problems.

Some relevant info: I set the terminal type to xterm-256 in iterm2 (same as in .bash_profile), and I set the background color to be transparent (so I can see things under the terminal). In my emacs config, I have this:

(defun remove-background-color ()
  "Useful for transparent terminal."
  (unless (display-graphic-p (selected-frame))
    (set-face-background 'default "unspecified-bg" (selected-frame))))

  ;; remove background color for both server and client
  (add-hook 'window-setup-hook 'remove-background-color)
  (add-hook 'server-visit-hook 'remove-background-color)

PS. The same problem persists after I removed above.

**Comment by 7696122** [comment]
plz, test by 72929bab36b3d77857cdfc6ce9f577ea236a2dc9 version. this is last version.

**Comment by huahaiy** [comment]
The latest version left 0 at the beginning of lines when scrolling up or down.

**Comment by 7696122** [comment]
I fixed. check now, plz.

**Comment by huahaiy** [comment]
Just tried the latest commit. It's indeed fixed. Thank you for the hard work.
